[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
# External
eframe = "0.35.0"
geo = "0.33"
geo-types = "0.7"

# Internal
aegis-core = { path = "crates/aegis-core" }
aegis-vector = { path = "crates/aegis-vector" }
aegis-raster = { path = "crates/aegis-raster" }
aegis-io = { path = "crates/aegis-io" }
aegis-geoprocessing = { path = "crates/aegis-geoprocessing" }
aegis-project = { path = "crates/aegis-project" }
aegis-render = { path = "crates/aegis-render" }

[workspace.lints.clippy]
# UM, ACTUALLY
pedantic = { level = "deny", priority = -1 }
# DEVELOPING LINTS
nursery = { level = "deny", priority = -1 }
# DENY PANICS
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
